### PR TITLE
Removed un-needed files, added .gitignore to project

### PR DESCRIPTION
**Pull request by FireBall1725**

### CODE REVIEW

**Comment by dtendr** [comment]
whoa its FireBall

**Comment by meepmeep22** [comment]
Wow, Diddent know he knew about "The project"

**Comment by FireBall1725** [comment]
i know almost everything :hamster:

**Comment by meepmeep22** [comment]
What did i just say??? Do you know?

**Comment by meepmeep22** [comment]
He's a wizard!

**Comment by FireBall1725** [comment]
one thing to note about this

You don't want the intellij idea files to be included, as they store preferences, and settings.  So if you clone the code to a new computer you will have to run the 'gradle setupdecompworkspace idea' again, but only on a new computer.

**Comment by meepmeep22** [comment]
Yah, Was going to ask you something. Ive been trying to run the code, But the execution main class for Gradlestart wont work, Dtendr says it works fine on his end, but not for me.

**Comment by FireBall1725** [comment]
I didn't look at the code.

**Comment by meepmeep22** [comment]
Here, Il send a screen shot

**Comment by dtendr** [comment]
I think FireBall just answered your question, before you even asked it

**Comment by meepmeep22** [comment]
Well, It just says it doesn't exist.

**Comment by FireBall1725** [comment]
Meep: did you setup your workspace first?  my suggestion, delete the folder, re-clone the project, then run "gradlew setupdecompworkspace idea" and then see if that works.

Also, because you use mac, you can download homebrew, and just install gradle, then you dont have to use the wrapper.

**Comment by meepmeep22** [comment]
Thanks fireball, I don't like mac anyways, Ive saved up quite a lot of money for a new laptop, so in a few days, il be running a windows machine, and porting over a bunch of applications.

**Comment by FireBall1725** [comment]
aww, well that sucks, I love mac, and mainly develop on mac.  Infact i did it the otherway around, and bought some high end mac stuff.

Here are a few reasons:
http://www.git-tower.com/

**Comment by meepmeep22** [comment]
well, I just don't like how they make nice hardware, but lock it down to osx almost completely, If you try to run anything else on it, It is barely comparable. I prefer open source machines.
What kind of software have you purchased?

**Comment by FireBall1725** [comment]
"I prefer open source machines."
Have you seen: https://www.apple.com/opensource/

Anyway, I have many development tools, and software that I use, most for OSX

**Comment by FireBall1725** [comment]
I should also mention that the reason i use apple for development is because im on a native unix environment which java development makes things really nice...

**Comment by meepmeep22** [comment]
Well, I see, Sorry about that.

**Pull request merged**
